name: computorbuild
on:
  push:
    branches:
      - master

jobs:
  computorticle:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: computo

      - name: Execute and convert myst to md
        shell: bash -l {0}
        run: |
          jupytext --to md,ipynb template-computo-myst.myst --execute
