name: computorbuild
on:
  push:
    branches:
      - master

jobs:
  computorticle:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: computo

      - name: Execute and convert myst to md
        shell: bash -l {0}
        run: |
          mkdir -p _build
          jupytext --to ipynb template-computo-myst.myst --execute --output _build/output.ipynb
          jupyter-nbconvert _build/output.ipynb --to markdown --output-dir _build/
          jupyter-nbconvert _build/output.ipynb --to html --output-dir _build/

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true

